openapi: 3.0.3
info:
  title: Asset Inventory API
  version: 1.0.0
  description: API for managing assets and listings in the inventory.

paths:
  /assets/{userAddress}:
    get:
      summary: Get all assets for a user
      description: |
        Retrieves all the assets owned by a user with the given address.
        The API requires an authentication token in the header, specifying either user or admin.
      parameters:
        - name: userAddress
          in: path
          description: The Ethereum address of the user.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  assets:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          description: Name of the token.
                        collection:
                          type: object
                          properties:
                            chainId:
                              type: integer
                              description: The chain ID of the collection.
                            name:
                              type: string
                              description: Name of the collection.
                            standard:
                              type: string
                              description: Type of token standard.
                        collectionAddress:
                          type: string
                          description: Address of the collection.
                        id:
                          type: string
                          description: ID of the asset.
                        image:
                          type: string
                          description: Link to the thumbnail image.
                        Listings:
                          type: array
                          items:
                            type: object
                            properties:
                              price:
                                type: integer
                                description: The price of the asset.
                              endTime:
                                type: integer
                                description: The end time of the listing.
                              status:
                                type: integer
                                description: The status of the listing.
                              saleData:
                                type: object
                                properties:
                                  expirationTimestamp:
                                    type: integer
                                    description: Expiration timestamp of the sale.
                                  Lister:
                                    type: string
                                    description: Address of the lister.
                                  ownerSignature:
                                    type: string
                                    description: Owner's signature.
                                  Price:
                                    type: integer
                                    description: Price of the asset.

  /assets/{addressOrShortUrl}/{nftId}:
    get:
      summary: Get asset details for an NFT
      description: |
        Retrieves additional information about an asset in the inventory.
      parameters:
        - name: addressOrShortUrl
          in: path
          description: The Ethereum address or short URL of the user's collection.
          required: true
          schema:
            type: string
        - name: nftId
          in: path
          description: The ID of the NFT.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  assets:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          description: Name of the token.
                        collection:
                          type: object
                          properties:
                            chainId:
                              type: integer
                              description: The chain ID of the collection.
                            shortUrl:
                              type: string
                              description: Short URL of the collection.
                            Name:
                              type: string
                              description: Name of the collection.
                            Standard:
                              type: string
                              description: Type of token standard.
                        collectionAddress:
                          type: string
                          description: Address of the collection.
                        id:
                          type: string
                          description: ID of the asset.
                        image:
                          type: string
                          description: Link to the asset image.
                        Listings:
                          type: array
                          items:
                            type: object
                            properties:
                              price:
                                type: integer
                                description: The price of the asset.
                              endTime:
                                type: integer
                                description: The end time of the listing.
                              status:
                                type: integer
                                description: The status of the listing.
                              saleData:
                                type: object
                                properties:
                                  expirationTimestamp:
                                    type: integer
                                    description: Expiration timestamp of the sale.
                                  Lister:
                                    type: string
                                    description: Address of the lister.
                                  ownerSignature:
                                    type: string
                                    description: Owner's signature.
                                  Price:
                                    type: integer
                                    description: Price of the asset.

  /{userAddress}/{assetId}:
    get:
      summary: Get asset details for an asset in the inventory
      description: |
        Retrieves detailed information about an asset in the inventory.
      parameters:
        - name: userAddress
          in: path
          description: The Ethereum address of the user.
          required: true
          schema:
            type: string
        - name: assetId
          in: path
          description: The ID of the asset.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    description: Name of the token.
                  collection:
                    type: object
                    properties:
                      chainId:
                        type: integer
                        description: The chain ID of the collection.
                      name:
                        type: string
                        description: Name of the collection.
                      artistName:
                        type: string
                        description: Name of the artist.
                      royaltyPercentage:
                        type: number
                        description: Royalty percentage.
                      splitWithAddresses:
                        type: array
                        items:
                          type: string
                        description: Addresses for split-with (for avatar images).
                      mintDate:
                        type: string
                        format: date-time
                        description: Mint date of the asset.
                      network:
                        type: string
                        description: Network (Ethereum).
                      assetAddress:
                        type: string
                        description: Address of the asset.
                      tokenStandard:
                        type: string
                        description: Token standard (ERC721).
                  price:
                    type: integer
                    description: Price of the asset.
                  status:
                    type: integer
                    description: Status of the asset.
                  assetImage:
                    type: string
                    description: Link to the asset image.
                  collectionThumbnailImage:
                    type: string
                    description: Link to the collection thumbnail image.
                  blockExplorerLink:
                    type: string
                    description: Block explorer link for the asset.
