openapi: 3.0.3
x-stoplight:
  id: 3ngl049ongtqy
info:
  title: Arttaca - OpenAPI 3.0
  description: |-
    This is the Arttaca API documentation based on the OpenAPI 3.0 specification.

    Some useful links:
    - [Arttaca](https://arttaca.io)
    - [The Arttaca GitHub repository](https://github.com/Arttaca)
  termsOfService: 'https://arttaca.io/'
  contact:
    email: leon@dandelionventures.io
    name: Leon Acosta
    url: leon@dandelionventures.io
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.0.11
externalDocs:
  description: Find out more about Arttaca
  url: 'https://arttaca.io/about'
servers:
  - url: 'http://localhost:8080'
tags:
  - name: order
    description: Everything about orders
    externalDocs:
      description: Find out more
      url: 'https://arttaca.io/about'
  - name: trade
    description: Everything about trades
    externalDocs:
      description: Find out more about Arttaca
      url: 'https://arttaca.io/about'
paths:
  /order:
    post:
      tags:
        - order
      summary: Add a new order to the Orders table
      description: Add a new order to the Orders table
      operationId: addOrder
      requestBody:
        description: Creates a new order in Order table
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
          application/xml:
            schema:
              $ref: '#/components/schemas/Order'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Order'
          multipart/form-data:
            schema:
              type: object
              properties:
                '':
                  type: string
                  x-stoplight:
                    id: 1
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
            application/xml:
              schema:
                $ref: '#/components/schemas/Order'
        '405':
          description: Invalid input
      security:
        - arttaca_auth:
            - 'write:order'
            - 'read:order'
  /order/{id}:
    get:
      tags:
        - order
      summary: get all orders from the Orders table
      description: get all orders from the Orders table
      operationId: addOrder
      requestBody:
        description: get all orders from the Orders table
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
          application/xml:
            schema:
              $ref: '#/components/schemas/Order'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Order'
          multipart/form-data:
            schema:
              type: object
              properties:
                '':
                  type: string
                  x-stoplight:
                    id: 1
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
            application/xml:
              schema:
                $ref: '#/components/schemas/Order'
        '405':
          description: Invalid input
      security:
        - arttaca_auth:
            - 'write:order'
            - 'read:order'
  /trade:
    post:
      tags:
        - trade
      summary: Add a new trade to the Trades table
      description: Add a new trade to the Trades table
      operationId: addTrade
      requestBody:
        description: Create a new trade in Trades
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Trade'
          application/xml:
            schema:
              $ref: '#/components/schemas/Trade'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Trade'
          multipart/form-data:
            schema:
              type: object
              properties:
                '':
                  type: string
                  x-stoplight:
                    id: z37n2blj91ix7
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trade'
            application/xml:
              schema:
                $ref: '#/components/schemas/Trade'
        '405':
          description: Invalid input
      security:
        - arttaca_auth:
            - 'write:trades'
            - 'read:trades'
components:
  schemas:
    Order:
      type: object
      xml:
        name: order
      x-stoplight:
        id: 3
      properties:
        userId:
          type: string
          example: eqf43q34q334f34434f
        eventId:
          type: string
          example: eqf43q34q334f34434f
        status:
          type: string
          description: 'The status of the order, COMPLETED | CANCELLED | ACTIVE | EXPIRED'
          enum:
            - COMPLETED
            - CANCELLED
            - ACTIVE
            - EXPIRED
          example: COMPLETED
      required:
        - userId
        - eventId
        - status
    Trade:
      type: object
      xml:
        name: trade
      x-stoplight:
        id: 4
        properties:
          orderId:
            type: string
            example: eqf43q34q334f34434f
          listingId:
            type: string
            example: eqf43q34q334f34434f
          quantity:
            type: integer
            format: int32
        required:
          - orderId
          - listingId
          - quantity
  requestBodies:
    Order:
      description: An order object that needs to be added to the 'Order' table
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Order"
        application/xml:
          schema:
            $ref: '#/components/schemas/Order'
        multipart/form-data:
          schema:
            type: object
            properties:
              '':
                type: string
                x-stoplight:
                  id: 6
    Trade:
      description: An trade object that needs to be added to the 'Trade' table
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Trade'
        application/xml:
          schema:
            $ref: '#/components/schemas/Trade'
        multipart/form-data:
          schema:
            type: object
            properties:
              '':
                type: string
                x-stoplight:
                  id: 7
  securitySchemes:
    arttaca_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'https://arttaca-authorization-url.io/'
          scopes:
            'write:order': modify orders in your account
            'read:order': view your orders
    api_key:
      type: apiKey
      name: api_key
      in: header
